{{- if and .Values.metrics.enabled .Values.metrics.serviceMonitor.enabled -}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "finberg.fullname" . }}
  labels: {{- include "finberg.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels: {{- include "finberg.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: http
      path: {{ .Values.metrics.serviceMonitor.path }}
      interval: {{ .Values.metrics.serviceMonitor.interval }}
{{- end -}}
