// ============================================================================
// FinScript compiler — AST → ES2022 module source string.
// The emitted module imports a Runtime object that provides ta.*, math.*,
// plot, alert, etc. The Runtime is supplied by the host (Web Worker).
// ============================================================================

import type { AstNode, ScriptNode } from './ast';
import { tokenize } from './lexer';
import { parse } from './parser';

export interface CompileOptions {
  /** Module name to import the runtime from. */
  runtimeImport?: string;
}

export interface CompileResult {
  ast: ScriptNode;
  code: string;
  inputs: Array<{ name: string; type: string; default: unknown; title?: string }>;
  warnings: string[];
}

export function compile(src: string, opts: CompileOptions = {}): CompileResult {
  const tokens = tokenize(src);
  const ast = parse(tokens);
  const runtimeImport = opts.runtimeImport ?? '@finberg/finscript/runtime';

  const inputs: CompileResult['inputs'] = [];
  const warnings: string[] = [];
  const lines: string[] = [
    `// Auto-generated by FinScript compiler — do not edit.`,
    `import { Runtime as __rt } from '${runtimeImport}';`,
    ``,
    `export const meta = ${JSON.stringify({ kind: ast.header.kind, title: ast.header.title, options: ast.header.options }, null, 2)};`,
    ``,
    `export function run(__ctx) {`,
    `  const ta = __rt.ta(__ctx);`,
    `  const math = __rt.math;`,
    `  const input = __rt.input(__ctx);`,
    `  const color = __rt.color;`,
    `  const plot = __rt.plot(__ctx);`,
    `  const plotshape = __rt.plotshape(__ctx);`,
    `  const hline = __rt.hline(__ctx);`,
    `  const fill = __rt.fill(__ctx);`,
    `  const alert = __rt.alert(__ctx);`,
    `  const alertcondition = __rt.alertcondition(__ctx);`,
    `  const { open, high, low, close, volume, time, bar_index } = __ctx.bar;`,
    ``,
  ];

  const indent = '  ';
  for (const node of ast.body) {
    lines.push(...emit(node, indent, inputs, warnings).split('\n'));
  }

  lines.push(`}`);

  return { ast, code: lines.join('\n'), inputs, warnings };
}

function emit(node: AstNode, indent: string, inputs: CompileResult['inputs'], warnings: string[]): string {
  switch (node.type) {
    case 'Decl': {
      const value = emitExpr(node.value, inputs);
      if (node.reassign) return `${indent}${node.name} = ${value};`;
      return `${indent}let ${node.name} = ${value};`;
    }
    case 'ExprStmt':
      return `${indent}${emitExpr(node.expr, inputs)};`;
    case 'If': {
      const t = emitExpr(node.test, inputs);
      const c = node.consequent.map(n => emit(n, indent + '  ', inputs, warnings)).join('\n');
      const a = node.alternate
        ? `\n${indent}} else {\n${node.alternate.map(n => emit(n, indent + '  ', inputs, warnings)).join('\n')}`
        : '';
      return `${indent}if (${t}) {\n${c}${a}\n${indent}}`;
    }
    default:
      warnings.push(`Top-level expression of type ${node.type} converted to no-op`);
      return `${indent}/* ${node.type} */`;
  }
}

function emitExpr(node: AstNode, inputs: CompileResult['inputs']): string {
  switch (node.type) {
    case 'Number':  return String(node.value);
    case 'String':  return JSON.stringify(node.value);
    case 'Bool':    return String(node.value);
    case 'Na':      return 'null';
    case 'Ident':   return node.name;
    case 'Unary': {
      const op = node.op === 'not' ? '!' : node.op;
      return `(${op}${emitExpr(node.argument, inputs)})`;
    }
    case 'Binary': {
      if (node.op === '.') {
        return `${emitExpr(node.left, inputs)}.${(node.right as { name: string }).name}`;
      }
      const op = node.op === 'and' ? '&&' : node.op === 'or' ? '||' : node.op;
      return `(${emitExpr(node.left, inputs)} ${op} ${emitExpr(node.right, inputs)})`;
    }
    case 'Call': {
      // Capture input.* declarations for the host
      if (node.callee.type === 'Binary' && node.callee.op === '.' &&
          (node.callee.left as { name: string }).name === 'input') {
        const inputType = (node.callee.right as { name: string }).name;
        const def = node.args[0];
        const titleArg = node.args.find(a => a.name === 'title');
        if (def) {
          inputs.push({
            name: `__in_${inputs.length}`,
            type: inputType,
            default: literal(def.value),
            title: titleArg ? String(literal(titleArg.value)) : undefined,
          });
        }
      }
      const args = node.args.map(a =>
        a.name ? `${a.name}: ${emitExpr(a.value, inputs)}` : emitExpr(a.value, inputs)
      ).join(', ');
      return `${emitExpr(node.callee, inputs)}(${args})`;
    }
  }
}

function literal(n: AstNode): unknown {
  switch (n.type) {
    case 'Number': return n.value;
    case 'String': return n.value;
    case 'Bool':   return n.value;
    case 'Na':     return null;
    default:       return null;
  }
}
